version: 2
jobs:
  build:
    docker:
      - image: yamamoi/sphinx-ci:wkhtmltopdf
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: create html
          command: |
            (cd sphinx-txt&&make html)
      - run:
          name: create pdf
          command: |
            (cd sphinx-txt&&wkhtmltopdf build/html/index.html build/output.pdf)
      - store_artifacts:
          path: ./sphinx-txt/build
