version: 2
jobs:
  build:
    docker:
      - image: yamamoi/sphinx-ci
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: create html
          command: |
            (cd sphinx-txt&&make html)
#      - run:
#          name: create pdf
#          command: |
#            (cd sphinx-txt&&make latexpdf)
      - run:
          name: check dir
          command: |
            pwd; ls sphinx-txt/build
      - store_artifacts:
          path: ./sphinx-txt/build

